FROM python:3.13-alpine
RUN apk add --no-cache python3-dev
WORKDIR /app
COPY ./src/rpc-jsonrpc/client.py /app/
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "client.py"]