# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x07\n\x05\x45mpty\"\x1a\n\tLongValue\x12\r\n\x05value\x18\x01 \x01(\x03\",\n\x0eMultLongValues\x12\x1a\n\x06values\x18\x01 \x03(\x0b\x32\n.LongValue\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"C\n\x0bVectorValue\x12\x1a\n\x05start\x18\x01 \x01(\x0b\x32\x0b.PointValue\x12\x18\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x0b.PointValue\"H\n\nPointValue\x12\r\n\x05xAxis\x18\x01 \x01(\x03\x12\r\n\x05yAxis\x18\x02 \x01(\x03\x12\r\n\x05zAxis\x18\x03 \x01(\x03\x12\r\n\x05\x63olor\x18\x04 \x01(\t2\xd3\x01\n\x11\x42\x65nchmarkServices\x12\x1a\n\x06VoidOP\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\"\n\x06LongOP\x12\n.LongValue\x1a\n.LongValue\"\x00\x12+\n\nMultLongOP\x12\x0f.MultLongValues\x1a\n.LongValue\"\x00\x12(\n\x08StringOP\x12\x0c.StringValue\x1a\x0c.StringValue\"\x00\x12\'\n\x07\x43lassOP\x12\x0c.VectorValue\x1a\x0c.VectorValue\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_LONGVALUE']._serialized_start=26
  _globals['_LONGVALUE']._serialized_end=52
  _globals['_MULTLONGVALUES']._serialized_start=54
  _globals['_MULTLONGVALUES']._serialized_end=98
  _globals['_STRINGVALUE']._serialized_start=100
  _globals['_STRINGVALUE']._serialized_end=128
  _globals['_VECTORVALUE']._serialized_start=130
  _globals['_VECTORVALUE']._serialized_end=197
  _globals['_POINTVALUE']._serialized_start=199
  _globals['_POINTVALUE']._serialized_end=271
  _globals['_BENCHMARKSERVICES']._serialized_start=274
  _globals['_BENCHMARKSERVICES']._serialized_end=485
# @@protoc_insertion_point(module_scope)
