# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BenchmarkServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoidOP = channel.unary_unary(
                '/BenchmarkServices/VoidOP',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                _registered_method=True)
        self.LongOP = channel.unary_unary(
                '/BenchmarkServices/LongOP',
                request_serializer=service__pb2.LongValue.SerializeToString,
                response_deserializer=service__pb2.LongValue.FromString,
                _registered_method=True)
        self.MultLongOP = channel.unary_unary(
                '/BenchmarkServices/MultLongOP',
                request_serializer=service__pb2.MultLongValues.SerializeToString,
                response_deserializer=service__pb2.LongValue.FromString,
                _registered_method=True)
        self.StringOP = channel.unary_unary(
                '/BenchmarkServices/StringOP',
                request_serializer=service__pb2.StringValue.SerializeToString,
                response_deserializer=service__pb2.StringValue.FromString,
                _registered_method=True)
        self.ClassOP = channel.unary_unary(
                '/BenchmarkServices/ClassOP',
                request_serializer=service__pb2.VectorValue.SerializeToString,
                response_deserializer=service__pb2.VectorValue.FromString,
                _registered_method=True)


class BenchmarkServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VoidOP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LongOP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultLongOP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StringOP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassOP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BenchmarkServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoidOP': grpc.unary_unary_rpc_method_handler(
                    servicer.VoidOP,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
            'LongOP': grpc.unary_unary_rpc_method_handler(
                    servicer.LongOP,
                    request_deserializer=service__pb2.LongValue.FromString,
                    response_serializer=service__pb2.LongValue.SerializeToString,
            ),
            'MultLongOP': grpc.unary_unary_rpc_method_handler(
                    servicer.MultLongOP,
                    request_deserializer=service__pb2.MultLongValues.FromString,
                    response_serializer=service__pb2.LongValue.SerializeToString,
            ),
            'StringOP': grpc.unary_unary_rpc_method_handler(
                    servicer.StringOP,
                    request_deserializer=service__pb2.StringValue.FromString,
                    response_serializer=service__pb2.StringValue.SerializeToString,
            ),
            'ClassOP': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassOP,
                    request_deserializer=service__pb2.VectorValue.FromString,
                    response_serializer=service__pb2.VectorValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BenchmarkServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BenchmarkServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BenchmarkServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VoidOP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BenchmarkServices/VoidOP',
            service__pb2.Empty.SerializeToString,
            service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LongOP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BenchmarkServices/LongOP',
            service__pb2.LongValue.SerializeToString,
            service__pb2.LongValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultLongOP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BenchmarkServices/MultLongOP',
            service__pb2.MultLongValues.SerializeToString,
            service__pb2.LongValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StringOP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BenchmarkServices/StringOP',
            service__pb2.StringValue.SerializeToString,
            service__pb2.StringValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassOP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BenchmarkServices/ClassOP',
            service__pb2.VectorValue.SerializeToString,
            service__pb2.VectorValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
